server:
  port: 8081

spring:
  application:
    name: core-processing-engine
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:paymentsdb}
    username: ${DB_USER:payments}
    password: ${DB_PASSWORD:payments}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

fraud:
  velocity:
    window-seconds: 60
    max-transactions: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.enterprise.core: INFO
