server:
  port: 8082

spring:
  application:
    name: payment-switch
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

fraud-risk-engine:
  url: ${FRAUD_URL:http://localhost:8083}

issuer:
  core-processing-engine:
    url: ${CORE_ENGINE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: payment-switch
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    com.enterprise.switchsvc: INFO
