version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  core-processing-engine:
    build: ./core-processing-engine
    depends_on:
      - postgres
      - kafka
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: paymentsdb
      DB_USER: payments
      DB_PASSWORD: payments
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  payment-switch:
    build: ./payment-switch
    depends_on:
      - kafka
      - core-processing-engine
    ports:
      - "8082:8082"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CORE_ENGINE_URL: http://core-processing-engine:8081

  fraud-risk-engine:
    build: ./fraud-risk-engine
    depends_on:
      - postgres
      - kafka
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: paymentsdb
      DB_USER: payments
      DB_PASSWORD: payments
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

volumes:
  pgdata:
