apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - core-processing-engine.yaml
  - payment-switch.yaml
  - fraud-risk-engine.yaml
  - tokenization-vault.yaml
  - card-management.yaml
  - clearing-settlement.yaml
  - api-gateway.yaml
  - ingress.yaml
